# Generated by Django 6.1.1 on 2026-09-30 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('precio', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'dentasmile_tratamiento',
            },
        ),
        migrations.CreateModel(
            name='CitaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=100)),
                ('paciente_telefono', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='dentasmile.tratamientomodel')),
            ],
            options={
                'db_table': 'dentasmile_cita',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
